apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-manager-deployment
  labels:
    app: inference-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-manager
  template:
    metadata:
      labels:
        app: inference-manager
    spec:
      containers:
      - name: inference-manager
        image: {{REGISTRY}}inference_manager:v1.0
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 5000
        env: 
          - name: FETCHER_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: bda-configmap
                key: FETCHER_BASE_URL
          - name: INFERENCE_MANAGER_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: bda-configmap
                key: INFERENCE_MANAGER_BASE_URL
          - name: RESULTS_CACHE_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: bda-configmap
                key: RESULTS_CACHE_BASE_URL          
          - name: SAMPLER_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: bda-configmap
                key: SAMPLER_BASE_URL
          - name: TRAINING_MANAGER_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: bda-configmap
                key: TRAINING_MANAGER_BASE_URL
          - name: ANALYZERS_WORKING_DIRECTORY
            value: ./analyzers
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerregcred

---
apiVersion: v1
kind: Service
metadata:
  name: inference-manager-service
spec:
  selector:
    app: inference-manager
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
