apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampler-deployment
  labels:
    app: sampler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampler
  template:
    metadata:
      labels:
        app: sampler
    spec:
      containers:
      - name: sampler
        image: {{REGISTRY}}sampler:v1.0
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 5000
        env: 
          - name: FETCHER_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: bda-configmap
                key: FETCHER_BASE_URL
          - name: INFERENCE_MANAGER_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: bda-configmap
                key: INFERENCE_MANAGER_BASE_URL
          - name: RESULTS_CACHE_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: bda-configmap
                key: RESULTS_CACHE_BASE_URL          
          - name: SAMPLER_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: bda-configmap
                key: SAMPLER_BASE_URL
          - name: TRAINING_MANAGER_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: bda-configmap
                key: TRAINING_MANAGER_BASE_URL
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerregcred

---
apiVersion: v1
kind: Service
metadata:
  name: sampler-service
spec:
  selector:
    app: sampler
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
